name: CI

env:
  SCRIPTS_FOLDER: scripts/
  DOCKER_IMAGE_NAME: custom-github-action
  DOCKER_IMAGE_TAG: latest

on:
  push:
    branches: 
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Authenticate with Docker
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build Docker image
        run: |
          docker build -t ${{ env.DOCKER_IMAGE_NAME }}:${{ env.DOCKER_IMAGE_TAG }} .
        working-directory: docker/
    
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

  check-files:
    runs-on: ubuntu-latest
    needs: [checkout, build]
    container:
      image: custom-github-action
    steps:        
      - name: Check required files
        run: |
          cd ${{ env.SCRIPTS_FOLDER }}
          chmod +x check_files.sh
          ./check_files.sh
        env:
          SCRIPTS_FOLDER: ${{ env.SCRIPTS_FOLDER }}

  check-ci:
    runs-on: ubuntu-latest
    needs: [checkout, build]
    container:
      image: custom-github-action
    steps:
      - name: CI check
        run: |
          cd ${{ env.SCRIPTS_FOLDER }}
          chmod +x check_ci.sh
          ./check_ci.sh rebase
        env:
          SCRIPTS_FOLDER: ${{ env.SCRIPTS_FOLDER }}

  check-header:
    runs-on: ubuntu-latest
    needs: [checkout, build]
    container:
      image: custom-github-action
    steps:
      - name: Header comments check
        run: |
          cd ${{ env.SCRIPTS_FOLDER }}
          chmod +x check_header.sh
          ./check_header.sh
        env:
          SCRIPTS_FOLDER: ${{ env.SCRIPTS_FOLDER }}