name: CI

env:
  SCRIPTS_FOLDER: scripts

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

  check-files:
    runs-on: ubuntu-latest
    needs: [checkout]
    steps:
      - name: Navigate to scripts folder
        run: cd ${{ github.workspace }}

      - name: Check required files
        run: ../scripts/check_files.sh

  check-ci:
    runs-on: ubuntu-latest
    needs: [checkout]
    steps:
      - name: Navigate to scripts folder
        run: cd ${{ github.workspace }}/${{ env.SCRIPTS_FOLDER }}

      - name: CI check
        run: ../scripts/check_ci.sh rebase

  check-header:
    runs-on: ubuntu-latest
    needs: [checkout]
    steps:
      - name: Navigate to scripts folder
        run: cd ${{ github.workspace }}/${{ env.SCRIPTS_FOLDER }}

      - name: Header comments check
        run: ../scripts/check_header.sh
