###
#
#  @file ci.yml
#  @copyright 2023-2024 SaruMC. All rights reserved.
#
#  @version 1.2.3
#  @author SaruMC
#  @date 2024-03-15
#
# This script executes all verifications for the runners
#
###

name: CI

env:
  WORKSPACE_FOLDER: ${{ github.workspace }}

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

  check-files:
    runs-on: ubuntu-latest
    needs: [checkout]
    steps:
      - name: Debug
        run: ls -la

      - name: Check required files
        run: ${{ env.WORKSPACE_FOLDER }}/scripts/check_files.sh

  check-ci:
    runs-on: ubuntu-latest
    needs: [checkout]
    steps:
      - name: CI check
        run: ${{ env.WORKSPACE_FOLDER }}/scripts//check_ci.sh rebase

  check-header:
    runs-on: ubuntu-latest
    needs: [checkout]
    steps:
      - name: Header comments check
        run: ${{ env.WORKSPACE_FOLDER }}/scripts//check_header.sh
