name: CI

env:
  SCRIPTS_FOLDER: scripts

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  debug:
    runs-on: ubuntu-latest
    needs: [checkout]
    steps:
      - name: Print environment variables
        run: | 
          echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"

      - name: Print current branch
        run: git rev-parse --abbrev-ref HEAD

      - name: Print current branch
        run: git rev-parse --abbrev-ref HEAD

  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

  check-files:
    runs-on: ubuntu-latest
    needs: [checkout]
    steps:
      - name: Navigate to scripts folder
        run: cd ${{ github.workspace }}/${{ env.SCRIPTS_FOLDER }}

      - name: Check required files
        run: ./check_files.sh

  check-ci:
    runs-on: ubuntu-latest
    needs: [checkout]
    steps:
      - name: Navigate to scripts folder
        run: cd ${{ github.workspace }}/${{ env.SCRIPTS_FOLDER }}

      - name: CI check
        run: ./check_ci.sh rebase

  check-header:
    runs-on: ubuntu-latest
    needs: [checkout]
    steps:
      - name: Navigate to scripts folder
        run: cd ${{ github.workspace }}/${{ env.SCRIPTS_FOLDER }}

      - name: Header comments check
        run: ./check_header.sh
